I did it, но это неточно
Annebula77/stellar-burger pull request #18
Opened 2023-04-17 11:45 UTC by Annebula77

2023-04-17 15:47 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную работу по добавлению контекста и DnD в ваш проект, добавил приятные подсказки для пользователя, хорошо организовали структуру стора по его функциональностям, реализовано переключение в навигации по ингредиентам, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Карточки ингредиентов в конструкторе следует сделать равными по ширине, вне зависимости от контента внутри (см. https://disk.yandex.ru/i/qknGaaVK_g3hbg)
- В массиве идентификаторов следует отправлять 2 булки: одну в начале, а другую в конце, так же, как они расположены в конструкторе;
- Для компонентов новых и измененных следует описать `PropTypes`, согласно комментариям к ревью;
- Не следует передавать весь набор ингредиентов в компонент категории, следует предварительно в родительском компоненте отфильтровать нужные данные, а затем передать уже туда;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-04-17 15:47 UTC, randomroot commented on src/components/burger-constructor/burger-constuctor.jsx
> +                text={`top-${bun.name} (верх)`}
🔴 **Нужно исправить:**

Аналогично ниже: следует убрать приставки `top-` и `bottom-`

2023-04-17 15:47 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.3",
🟡 **Можно улучшить:**

Т.к. библиотека не используется в рамках проекта, то её можно безопасно убрать

2023-04-17 15:47 UTC, randomroot commented on src/components/main/main.jsx
> +export default Main;
🔴 **Нужно исправить:**

Для данного компонента следует прописать его `PropTypes`

2023-04-17 15:47 UTC, randomroot commented on src/services/reducers/burger-constructor-reducer.jsx
> +      return {
🟡 **Можно улучшить:**

Можно вернуть `initialState`

2023-04-17 15:47 UTC, randomroot commented on src/services/reducers/ingredient-reducer.jsx
> +  сurrentIngredient: {},
🟡 **Можно улучшить:**

В качестве пустого значения не рекомендуется использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2023-04-17 15:47 UTC, randomroot commented on src/services/reducers/ingredients-reducer.jsx
> +  console.log("action", action);
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2023-04-17 15:47 UTC, randomroot commented on src/services/actions/burger-constructor-action.jsx
> +  const key = uniqid();
🟡 **Можно улучшить:**

Для булочки указание ключа необязательно, т.к. она не участвует в функциях `map`

2023-04-17 15:47 UTC, randomroot commented on src/components/burger-constructor/burger-constuctor.jsx
> +    () => ingredients.filter((item) => item.type !== "bun"),
🟡 **Можно улучшить:**

Данная проверка более не требуется, т.к. в `ingredients` будут только начинка и соусы, булка в отдельной переменной живет теперь :)

2023-04-17 15:47 UTC, randomroot commented on src/components/burger-constructor/burger-constuctor.jsx
> +    const bunId = bun ? [bun._id] : []; // если есть булка, добавляем её ID в массив
🟡 **Можно улучшить:**

Здесь не целесообразно создавать еще один массив, не отправляйте заказ без булки и сразу добавляйте её ID в результат - так будет удобнее и не займет лишнюю память :)

2023-04-17 15:47 UTC, randomroot commented on src/components/burger-constructor/burger-constuctor.jsx
> +                Молодец! А теперь добавь сюда начинки, и будет тебе вкуснее 😋
🟢 **Отлично:**

Классно, что общаетесь с пользователем 👍

2023-04-17 15:47 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [current, setCurrent] = useState('bun');
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2023-04-17 15:47 UTC, randomroot commented on src/components/ingredient/ingredient.jsx
> +function Ingredient({ ingredient, onClick }) {
🔴 **Нужно исправить:**

Следует описать `PropTypes` для `onClick`

2023-04-17 15:47 UTC, randomroot commented on src/components/ingredient/ingredient.jsx
> +  const counter = useMemo(
🟡 **Можно улучшить:**

1) Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2) Возвращайте из `useMemo` напрямую `count` вместо стрелочной функции, чтобы не вызывать его ниже два раза

2023-04-17 15:47 UTC, randomroot commented on src/components/ingredients-category/ingredients-category.jsx
> +        {ingredients.map((ingredient) => {
🔴 **Нужно исправить:**

Следует предварительно в родительском компоненте отфильтровать нужные данные, а затем передать уже сюда. Не следует передавать полный набор данных дочерним компонентам

2023-04-17 17:36 UTC, Annebula77 commented on src/components/burger-constructor/burger-constuctor.jsx
> +                Молодец! А теперь добавь сюда начинки, и будет тебе вкуснее 😋
Спасибо)

2023-04-17 21:58 UTC, Annebula77 commented on src/components/ingredient/ingredient.jsx
> +  const counter = useMemo(
как в редаксе прописать counter не додумалась, стрелочную функцию убрала)

2023-04-18 10:22 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-04-18 10:22 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        return item.type === "bun"
🟡 **Можно улучшить:**

Здесь также можно использовать `TabItems`

2023-04-20 13:39 UTC, merged