Month 9/step 2
Annebula77/stellar-burger pull request #33
Opened 2023-05-30 16:33 UTC by Annebula77

2023-05-30 17:21 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сокеты открываются и закрываются согласно брифу
- В Веб-сокете нет привязки к конкретному `Url`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- При открытии конкретного заказа из Истории по прямой ссылке - пустая страница.

<img width="1440" alt="Снимок экрана 2023-05-30 в 20 14 11" src="https://github.com/Annebula77/stellar-burger/assets/60173362/db628e0f-7a7e-493d-aa43-308521902fff">

- Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей. Иначе сейчас при заходе на страницу "История заказов" сначала на пару секунд видно данные из "Ленты заказов".

- В проекте должен быть универсальный socketMiddleware. Нужно передавать объект с типами в вызов для повышения универсальности и независимости от внешних данных.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-30 17:21 UTC, andryxxa93 commented on src/utils/socketMiddleWare.jsx
> +          socketAllOrders.onmessage = event => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-05-30 17:21 UTC, andryxxa93 commented on src/components/ingredient/ingredient.jsx
>  function Ingredient({ ingredient, onClick }) {
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-05-31 20:48 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-31 21:11 UTC, Annebula77 commented
@andryxxa93 спасибо!

2023-06-01 07:52 UTC, merged