Month 7/step 1
Annebula77/stellar-burger pull request #4
Opened 2023-03-11 22:51 UTC by Annebula77

2023-03-12 05:12 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно исправить ошибку в консоли: <https://disk.yandex.com/i/qAk0YiJwQ0KEBA>;

- У файла `prop-types.jsx`, должно быть расширение `.js`, т.к. там нет `.jsx` кода;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  // в ingredientType уже есть `.isRequired`
  data: PropTypes.arrayOf(ingredientType).isRequired;
  ```

  Проверьте во всём проекте.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constuctor.jsx
> +        </li>
**Надо исправить:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

Так вам не нужно будет делать фильтрацию от булок и обращаться по индексам.

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +            if (props.type === "bun") {
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        </ul>
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  type: cardProp
**Надо исправить:**

Переименуйте пропс `type` в `data`.

Также, тут необходимо использовать `arrayOf` и указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
// в ingredientType уже есть `.isRequired`, как и у вас.
data: PropTypes.arrayOf(ingredientType).isRequired;
```

Лучше сразу использовать пропсы, а не брать массив из файла (вам в любом случае нужно будет оттуда брать данные, но это вы должны делать в родительском компоненте) ))

2023-03-12 05:12 UTC, ArslanDev666 commented on src/utils/prop-types.jsx
> +const cardProp = PropTypes.shape({
**Надо исправить:**

Лучше переименовать в `ingredientType`;

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/ingredient/ingredient.jsx
> +};
**Надо исправить:**

Описаны не все пропсы, которые используются.

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/ingredient/ingredient.jsx
> +function Ingredient(props) {
**Надо исправить:**

Лучше использовать обьект в качестве пропса: 

```js 
function Ingredient({ingredient}) {...}

Ingredient.propTypes = {
  ingredient: ingredientType
}
```

2023-03-12 05:12 UTC, ArslanDev666 commented on src/components/tabs/tabs.jsx
> +    <div style={{ display: 'flex' }}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-03-12 10:30 UTC, Annebula77 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  type: cardProp
я изменила код, исходя из ваших рекомендаций. Мне кажется в некоторых проверках нет не обходимости. Проверьте, пожалуйста.

2023-03-13 07:38 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец! Можете приступать к выполнению финальной части задания. (Работа не принята, для того чтобы была возможность отправить финальную часть задания)**

- Все замечания были исправлены;

2023-03-13 07:38 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constuctor.jsx
> +  }, [ingredientsData]); // eslint-disable-line
Вот это лучше убрать `eslint-disable` позже) когда будете делать финальную часть задания.

2023-03-13 07:38 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constuctor.jsx
> +  }, [ingredients]);
**Можно лучше:**

Тут нет необходимости в `useMemo`, потому что в любом случае при изменении ингредиентов будет ререндер) поэтому лучше оставить как было))

2023-03-13 07:38 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +}
**Надо исправить:**

Лучше вынести в отдельный компонент, и не забудьте перенести `prop-types`;

2023-03-13 07:38 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const sauces = useMemo(() => ingredientsData.filter((ingredient) => ingredient.type === 'sauce'), [ingredientsData]); // eslint-disable-line
Вот это лучше убрать `eslint-disable` позже) когда будете делать финальную часть задания.

2023-03-13 07:38 UTC, ArslanDev666 commented on src/components/ingredient/ingredient.jsx
> +    <li className={styles.element} key={_id}>
**Надо исправить:**

Тут не нужен атрибут `key`, мы ведь ничего тут не итерируем)) 

https://ru.react.js.org/docs/lists-and-keys.html

2023-03-13 07:38 UTC, ArslanDev666 commented on src/components/ingredient/ingredient.jsx
> +function Ingredient({ _id, image, price, name }) {
**Надо исправить:**

Как я и говорил ранее, вам стоит использовать тут цельный обьект, либо передавать эти свойства:

```js
// ingredient-category.jsx
<Ingredient key={ingredient._id} ingredient={ingredient} />

// Ingredient.jsx
function Ingredient({ ingredient }) {
  const {_id, image, price, name} = ingredient 
}

Ingredient.propTypes = {
  ingredient: ingredientType
}
```

2023-03-21 04:17 UTC, merged